resources:
  repositories:
  - repository: mirepoix
    type: github
    name: xamarin/mirepoix
    ref: refs/heads/master
    endpoint: GitHub-XamarinInteractive

trigger:
- master

pr:
- master

jobs:
- job: macOS
  queue: Hosted macOS Preview
  steps:
  - template: .vsts-ci-steps.yml

- job: Linux
  queue: Hosted Ubuntu 1604
  steps:
  - template: .vsts-ci-steps.yml

- job: Windows
  queue: Hosted VS2017
  steps:
  - template: .vsts-ci-steps.yml

  - script: |
      dotnet pack
    displayName: Pack Libraries

  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: Artifacts
      PathtoPublish: _artifacts
    displayName: Publish Artifacts