steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: 2.1.500
  displayName: Install .NET Core

# This script runs both via bash (macOS/Linux) and cmd (Windows).
# Keep it both valid bash and batch or break it out conditionally.
- script: |
    echo System Environment
    set
    echo .NET Core Info
    dotnet --info
  displayName: Dump Environment

- script: |
    dotnet msbuild /restore
  displayName: Restore

- script: |
    dotnet msbuild /noautoresponse /v:detailed /bl:_artifacts/build.binlog mirepoix.proj
  displayName: Build

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*.Tests.csproj'
    arguments: '--no-restore --no-build'
  displayName: Run xUnit Tests
  continueOnError: true